### ISSUE TITLE
NPS已经彻底在运营商防火墙层面被拦截,建议增加TLS混淆.

### ISSUE THREAD

**Issue by lishiren-admin** [yisier/nps#105]
在多个江苏盐城的移动宽带中测试过,NPC客户端均无法正常与服务端通,电脑切换到联通的4G热点恢复正常,后续同一台服务器搭建FRP 使用TLS混淆,穿透成功了.
NPS自带没有TLS功能,无法混淆特征,运营商层面的防火墙已经开始针对NPS的规则进行拦截,估计命不久矣

**Comment by Zeyu-ZEYU** [comment]
这不是针对nps，这是针对未知流量。不同运营商对未知流量有不同措施。建议用frp或者v2ray开启TLS进行反向代理。

**Comment by Coflys** [comment]
我这边办公室换了一个区，发现nps用不起了，已经该用 frp

**Comment by Limour-dev** [comment]
加一层混淆效果怎么样？比如hysteria的[QUIC伪装](https://limour-blog.github.io/Protocol-for-intranet-penetration-based-on-QUIC)

**Comment by yisier** [comment]
可以尝试下 [0.27.01 版本](https://github.com/yisier/nps/releases/tag/v0.27.01)
