### ISSUE TITLE
npc客户端断开连接

### ISSUE THREAD

**Issue by liuliwei91** [yisier/nps#107]
不定时断开连接，npc日志中没有任何断开记录。进程还在。
系统是ubuntu 22.04.1，是不是兼容性问题？
重启npc就可以连上。

**Comment by juelianfy** [comment]
2023/08/21 08:26:27.700 [E] [control.go:231]  timeout
2023/08/21 08:26:27.700 [E] [client.go:158]  connect to  redfafdshdddin.f3322.net:65324 error: timeout
我是这样的问题，也是重启一次NPC就正常了

**Comment by xiaoluhong** [comment]
@juelianfy f3322.net 动态域名解析吧？ 这种动态域名解析在更新域名解析时候可能有短时间的 dns 解析不生效，客户端 dns 查询假设存在缓存，因为之前的域名解析已经变动，而客户端又缓存了之前 dns 查询 session，就会导致客户端一直连接不上。重启 客户端之后释放了查询缓存就又可以正常连接。像这种情况我们平时在其他应用的维护中也时不时遇到。
