### ISSUE TITLE
增加客户端到服务端的tls混淆

### ISSUE THREAD

**Issue by ac-sc** [yisier/nps#113]
目前已经有多家安全厂商系统能对nps流量进行识别，能否增加客户端到服务端连接加密呢？

**Comment by FQrabbit** [comment]
>Are both TCP and KCP recognizable?  

 请问TCP和KCP都能识别吗?

**Comment by ac-sc** [comment]
是的

**Comment by ac-sc** [comment]
> >Are both TCP and KCP recognizable?  
> 
>  请问TCP和KCP都能识别吗?
> 

是的

**Comment by juelianfy** [comment]
什么运营商要拦截这个？我们这里电信移动都不会拦截呀？你又不是病毒

**Comment by juelianfy** [comment]
自己放行不就好了，如果你不是网管，你架这个干什么？让网管给你放行。

**Comment by yisier** [comment]
可以尝试下  [0.27.01 版本](https://github.com/yisier/nps/releases/tag/v0.27.01)
