### ISSUE TITLE
服务端正常，客户端不断重连，无法连接上，报read session unpack from connection err 

### ISSUE THREAD

**Issue by eloasankey** [yisier/nps#122]
2023/08/28 02:51:53.211 [I] [npc.go:236]  Client closed! It will be reconnected in five seconds
2023/08/28 02:51:58.255 [I] [client.go:72]  Successful connection with server 123.*.*.*:8024
2023/08/28 02:51:58 mux: read session unpack from connection err read tcp 10.10.10.3:58237->123.*.*.*:8024: wsarecv: An existing connection was forcibly closed by the remote host.
2023/08/28 02:51:58 close mux
2023/08/28 02:51:58.305 [W] [client.go:165]  accpet error,the conn has closed
2023/08/28 02:51:58.306 [E] [client.go:92]  Accept server data error read tcp 10.10.10.3:58236->123.*.*.*:8024: use of closed network connection, end this service
2023/08/28 02:51:58.306 [I] [npc.go:236]  Client closed! It will be reconnected in five seconds
2023/08/28 02:52:03.349 [I] [client.go:72]  Successful connection with server 123.*.*.*:8024
2023/08/28 02:52:03 mux: read session unpack from connection err read tcp 10.10.10.3:58239->123.*.*.*:8024: wsarecv: An existing connection was forcibly closed by the remote host.
2023/08/28 02:52:03 close mux
2023/08/28 02:52:03.411 [W] [client.go:165]  accpet error,the conn has closed
2023/08/28 02:52:03.411 [E] [client.go:92]  Accept server data error read tcp 10.10.10.3:58238->123.*.*.*:8024: use of closed network connection, end this service
2023/08/28 02:52:03.411 [I] [npc.go:236]  Client closed! It will be reconnected in five seconds

请问下循环报这种错误，是什么原因，有啥解决办法吗？

**Comment by mmdt-123456** [comment]
我的直接报链接超时，端口啥的都开通了，不知道什么原因

**Comment by yisier** [comment]
网络或者防火墙问题吧
