### ISSUE TITLE
代理stable Diffusion webui时候，websocket连接不稳定， 经常报连接失败。

### ISSUE THREAD

**Issue by absir** [yisier/nps#132]
![image](https://github.com/yisier/nps/assets/4344078/ca893833-1215-4d5b-993f-e7f90cebebd3)

**Comment by absir** [comment]
正常情况下 websocket请求会快速处理完毕
![image](https://github.com/yisier/nps/assets/4344078/1f18d6bc-d259-4f52-9911-0b11100048a6)

错误情况下会一致挂再待处理， 应该websocket 或未正确同步代理客户端请求已经完成的状态
![image](https://github.com/yisier/nps/assets/4344078/2818f4f7-9507-484b-b7c3-f17798d200d7)

![image](https://github.com/yisier/nps/assets/4344078/30be0c98-6c79-4adf-a8ca-c6fec2859555)

**Comment by zuilintan** [comment]
Look Here：
https://github.com/ehang-io/nps/issues/502#issuecomment-1971485684

**Comment by yisier** [comment]
> Look Here： [ehang-io#502 (comment)](https://github.com/ehang-io/nps/issues/502#issuecomment-1971485684)
> 
> Nginx config incorrect
👍
