### ISSUE TITLE
nps链接异常

### ISSUE THREAD

**Issue by yuehun** [yisier/nps#135]
![微信截图_20231204193901](https://github.com/yisier/nps/assets/24507941/1b0fa40b-b828-4235-a98c-b97c439078c2)
刚启动，还没开始链接呢，日志里面这么多链接记录是啥意思

**Comment by Septemberrrrrr** [comment]
这是被人攻击了吧，你可以搜索一下这些ip的地区，大概率都是外国的

**Comment by yuehun** [comment]
并不是被攻击，换一个服务器，换一个域名刚启动也这样
