### ISSUE TITLE
全局黑名单IP

### ISSUE THREAD

**Issue by black-zyp** [yisier/nps#139]
您好我想问一下作者，这个全局黑名单IP的限制规则是什么呀，有具体的限制列表嘛，因为我在使用的时候出现了使用代理无法连接配置了额nps的目标服务器

**Comment by yisier** [comment]
![image](https://github.com/yisier/nps/assets/26956516/1b9516a9-07e2-4074-8c75-27cb35cdced3)
很简单啊，添加到全局黑名单的IP，就无法访问 nps 暴露出来的端口了
