### ISSUE TITLE
大佬，安卓好做嘛

### ISSUE THREAD

**Issue by JeazW** [yisier/nps#145]
想给电视装一个

**Comment by yhl452493373** [comment]
装软路由上

**Comment by SianHH** [comment]
安卓客户端软件，使用jna调用so实现，由于个人需求开发，只能支持tcp，不支持kcp，下载地址：https://reve.sian.one/s/2Esp

**Comment by ppllpig** [comment]
> 安卓客户端软件，使用jna调用so实现，由于个人需求开发，只能支持tcp，不支持kcp，下载地址：https://reve.sian.one/s/2Esp

版本不匹配，不是最新版的吗？

**Comment by JeazW** [comment]
> 安卓客户端软件，使用jna调用so实现，由于个人需求开发，只能支持tcp，不支持kcp，下载地址：https://reve.sian.one/s/2Esp

感谢感谢，非常好用

**Comment by JeazW** [comment]
> 安卓客户端软件，使用jna调用so实现，由于个人需求开发，只能支持tcp，不支持kcp，下载地址：https://reve.sian.one/s/2Esp

大佬我只想知道您这个cloudreve为何下载速度这么快，怎么优化的，是大带宽公网服务器吗😀

**Comment by JsonSong89** [comment]
> > 安卓客户端软件，使用jna调用so实现，由于个人需求开发，只能支持tcp，不支持kcp，下载地址：https://reve.sian.one/s/2Esp
> 
> 大佬我只想知道您这个cloudreve为何下载速度这么快，怎么优化的，是大带宽公网服务器吗😀

看最后文件的下载地址就知道了,走的是onedrive的公网,不是他的服务器
