### ISSUE TITLE
linux386版本npc在iOS的iSH虚拟机里运行出现index out of range错误

### ISSUE THREAD

**Issue by tinyluck** [yisier/nps#146]
**Describe the bug**
linux386版本npc在iOS的iSH虚拟机里运行出现index out of range错误

**To Reproduce**
1. 在iOS的iSH虚拟机里运行linux386版本npc
2. 报错panic: runtime error: index out of range [5] with length 5

**Expected behavior**
期望能正常运行

**Screenshots or logs**
panic: runtime error: index out of range [5] with length 5

**Client (please complete the following information):**
 - OS: iOS 17.2.1 with iSH 1.3.2
 - ARCH: [iSH虚拟x86]
 - Version [0.27.0]

**Additional context**
是gopsutil的bug，已在v3.23.10修复。本项目使用的版本是v3.21.3。期望能够更新。
v3.23.10
@[shirou](https://github.com/shirou) shirou released this Nov 1, 2023
What's Changed
cpu
fix(linux): validate cpu fields length before accessing index by @JanDeDobbeleer in https://github.com/shirou/gopsutil/pull/1544

**Comment by yisier** [comment]
已修复
