### ISSUE TITLE
可以考虑兼容官方0.26.10的版本吗

### ISSUE THREAD

**Issue by bxjg1987** [yisier/nps#152]
我们有设备已经在客户那里用起来了，是官方的0.26.10的版本。
我尝试部署0.27.01的服务端，发现老的，官方的0.26.10的客户端连接不上来，只好又切换回官方老的版本了。

请问可以支持向后兼容吗？，就是让官方老的0.26.10的客户端也能连这个库的0.27.01的服务端

**Comment by Oaklight** [comment]
用新版0.26.17就可以了
