### ISSUE TITLE
Docker中，NPC与服务端使用HTTP连接无效，TLS恒为false，无法修改

### ISSUE THREAD

**Issue by zuilintan** [yisier/nps#160]
![image](https://github.com/yisier/nps/assets/34953840/5f7fe1b8-a03d-41d0-bffe-8693a870b134)

但在非Docker的NPC中，连接正常：
![image](https://github.com/yisier/nps/assets/34953840/2330c2ac-aaa1-4924-b187-e18264882a42)

**Comment by zuilintan** [comment]
并且 无配置文件 方式，连接无效

**Comment by FangchaoChen** [comment]
docker 你是使用配置文件的吗？我也遇到同样问题，但是后来发现，命令启动没问题，配置文件启动需要修改下
![微信图片_20240527112817](https://github.com/yisier/nps/assets/160470167/54a69b64-4ed5-47d2-af8b-eaf7f5cee200)

**Comment by zuilintan** [comment]
> docker 你是使用配置文件的吗？我也遇到同样问题，但是后来发现，命令启动没问题，配置文件启动需要修改下 ![微信图片_20240527112817](https://private-user-images.githubusercontent.com/160470167/333948184-54a69b64-4ed5-47d2-af8b-eaf7f5cee200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODEzMzAsIm5iZiI6MTcxNjc4MTAzMCwicGF0aCI6Ii8xNjA0NzAxNjcvMzMzOTQ4MTg0LTU0YTY5YjY0LTRlZDUtNDdkMi1hZjhiLWVhZjdmNWNlZTIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMzM3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2JlZjRkZDJlOGQ4NjAxMWQzYTJkNzg5YTU2MGZkMmUzNTZmYzMyOGMwZjQyZTRiNjQ2Nzc3OGYyMjc3MmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1zhDrM5UeYBSKqrOzRnghaFyBoNKcRsui899DZvpaXE)

谢谢, 的确如此

**Comment by yisier** [comment]
已修复。
