### ISSUE TITLE
解压完压缩包，执行./nps install后，nps start启动无回显，ps -ef | grep nps无相关进程，lsof -i:8080也没有

### ISSUE THREAD

**Issue by IIIgnac** [yisier/nps#161]
![image](https://github.com/yisier/nps/assets/54889331/dfac3aee-8ebd-40c8-8ccb-804a20e5e9c7)

**Comment by yisier** [comment]
install 功能在不同的操作系统中实现方式不一样，不太稳定，建议使用docker
