### ISSUE TITLE
 openwrt npc 永远停在了0.26.10 有没有哪个大佬顺便更新一下 arm 和 x86的 客户端和依赖

### ISSUE THREAD

**Issue by josbu** [yisier/nps#164]
openwrt npc 永远停在了0.26.10 有没有哪个大佬顺便更新一下 arm 和 x86的 客户端和依赖

**Comment by noahyann** [comment]
用SSH上去，手动把执行文件替换一下。openwrt软件包要更新是你的源让不让更新的问题

**Comment by josbu** [comment]
> 用SSH上去，手动把执行文件替换一下。openwrt软件包要更新是你的源让不让更新的问题

这个执行文件在哪知道嘛
