### ISSUE TITLE
nps无法启动，create_captcha函数不存在

### ISSUE THREAD

**Issue by hs233666** [yisier/nps#166]
2024/04/07 12:46:09.586 [I] [nps.go:202]  the version of server is 0.26.10 ,allow client core version to be 0.26.0
2024/04/07 12:46:09.901 [I] [connection.go:36]  server start, the bridge type is tcp, the bridge port is 28024
2024/04/07 12:46:09.903 [I] [server.go:200]  tunnel task  start mode：httpHostServer port 0
2024/04/07 12:46:09.903 [I] [connection.go:71]  web management start, access port is 28080
2024/04/07 12:46:09.903 [I] [connection.go:62]  start https listener, port is 44443
2024/04/07 12:46:09.903 [I] [connection.go:53]  start http listener, port is 44480
2024/04/07 12:46:09.916 [E] [template.go:227]  parse template err: login/index.html template: login/index.html:70: function "create_captcha" not defined
2024/04/07 12:46:09.916 [W] [hooks.go:80]  template: login/index.html:70: function "create_captcha" not defined
panic: template: login/index.html:70: function "create_captcha" not defined

goroutine 13 [running]:
github.com/astaxie/beego.InitBeforeHTTPRun()
        /home/runner/go/pkg/mod/github.com/exfly/beego@v1.12.0-export-init/beego.go:104 +0x1ef
ehang.io/nps/server/proxy.(*WebServer).Start(0xc000370340, 0xc0000acd80, 0xc0a640)
        /home/runner/work/nps/nps/server/proxy/tcp.go:71 +0x33b
ehang.io/nps/server.StartNewServer(0x6d78, 0xc0000acd80, 0xc00002647b, 0x3, 0x3c)
        /home/runner/work/nps/nps/server/server.go:104 +0x2fd
created by main.run
        /home/runner/work/nps/nps/cmd/nps/nps.go:212 +0x265

**Comment by getda** [comment]
这个问题怎么解决呢

**Comment by getda** [comment]
> 这个问题怎么解决呢

我直接把 view login页面中的验证码那块代码给删除了 正常使用

**Comment by yisier** [comment]
0.26.10 ，为什么不升级nps 版本，却替换了新版本的 html 文件呢
