### ISSUE TITLE
客户端IP地址显示不全

### ISSUE THREAD

**Issue by djylb** [yisier/nps#167]
当客户端使用ipv6连接时地址只显示了“[2001”。
![Snipaste_2024-04-13_02-49-49](https://github.com/yisier/nps/assets/34548095/4e388960-1b5b-4dc5-a4c7-b95cbb53d4ab)

**Comment by djylb** [comment]
https://github.com/djylb/nps
修复代码见上面，希望有空合并一下

**Comment by xinjiawei** [comment]
同样的问题, 服务端版本是0.26.20, 希望能解决
