### ISSUE TITLE
19版本web页面版本号未同步

### ISSUE THREAD

**Issue by zuilintan** [yisier/nps#174]
依然是18
![IMG_20240605_011620](https://github.com/yisier/nps/assets/34953840/ea5fe130-b76d-4fa5-8b20-981d2785edf5)

**Comment by tinyluck** [comment]
我用window版server测试，正常显示0.26.19。你再重启nps服务看看，控制台里显示的版本号是多少，网页里显示的版本号是多少。

**Comment by zuilintan** [comment]
> 我用window版server测试，正常显示0.26.19。你再重启nps服务看看，控制台里显示的版本号是多少，网页里显示的版本号是多少。

依然不行
[linux_amd64_server.tar.gz](https://github.com/yisier/nps/releases/download/v0.26.19/linux_amd64_server.tar.gz)

**Comment by zuilintan** [comment]
莫名奇妙又好了, 可能是缓存导致
