### ISSUE TITLE
请问有docker的npc吗？

### ISSUE THREAD

**Issue by ppllpig** [yisier/nps#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ilay1678** [comment]
我fork了一份本仓库并用action自动打包docker 镜像并发布到docker-hub ，你可以用我打包的 镜像名 `ilay/npc`

**Comment by yisier** [comment]
我也发布了一个镜像，目前的改动对客户端没什么影响，老版本的客户端也可以使用
  https://hub.docker.com/r/yisier1/npc
