### ISSUE TITLE
客户端限速单位不统一

### ISSUE THREAD

**Issue by sxfman** [yisier/nps#185]
<img width="298" alt="1720085917323" src="https://github.com/yisier/nps/assets/41533853/8a855fe0-4182-4f8c-8fb9-bc646cedd7f2">
设置限速的时候单位是：KB/S

<img width="664" alt="1720086025726" src="https://github.com/yisier/nps/assets/41533853/a29a381b-d779-4611-a1f8-bbe12ad9cb86">
显示的时候单位是：kb/s
真实的数值到底在哪个为准？

**Comment by gdzjy** [comment]
看提交记录，开发已经修复了。

**Comment by yisier** [comment]
https://github.com/yisier/nps/releases/tag/v0.26.20
