### ISSUE TITLE
能否加一个自动将攻击的ip加入黑名单的功能

### ISSUE THREAD

**Issue by gloryhui** [yisier/nps#187]
快被扫描扫麻了

**Comment by yisier** [comment]
可以自己写个脚本统计IP，加入到黑名单里

**Comment by black-zyp** [comment]
@yisier 大佬 这样统计是非试试的 现在有后端的接口直接在后台更新黑名单目录吗，还是说写脚本统计一段时间内的，然后手动在页面加到黑名单里，希望大佬解答
