### ISSUE TITLE
tls加密

### ISSUE THREAD

**Issue by cszheng1** [yisier/nps#2]
可以增加客户端和服务端连接使用tls加密这个功能吗

**Comment by yisier** [comment]
有这个计划的

**Comment by zhoucheng45** [comment]
可以搞一个像ZeroTier那样的功能吗？  直接把家里的电脑和公司的电脑组成一个局域网。

**Comment by qxa792** [comment]
貌似配置下代理就可以了吧，就是代理功能没授权，有点不安全

**Comment by zhoucheng45** [comment]
您好，您的邮件我已经收到！请放心！，我会尽快回复！若有急事，请拨打15927970512！，祝工作顺利，身体健康！

**Comment by sicode** [comment]
> 的功能吗？ 直接把家里的电脑和公

估计不会，两者不同方向

**Comment by zhoucheng45** [comment]
您好，您的邮件我已经收到！请放心！，我会尽快回复！祝工作顺利，身体健康！

**Comment by yisier** [comment]
可以尝试下  [0.27.01 版本](https://github.com/yisier/nps/releases/tag/v0.27.01)
