### ISSUE TITLE
请问Docker镜像下载地址是什么

### ISSUE THREAD

**Issue by EarlmanCn** [yisier/nps#201]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oaklight** [comment]
请阅读README，都写在里面了
https://github.com/yisier/nps#%E8%AF%B4%E6%98%8E

**Comment by EarlmanCn** [comment]
> 提问前请阅读README并做简单的搜索，都写在里面了 https://github.com/yisier/nps#%E8%AF%B4%E6%98%8E

感谢
