### ISSUE TITLE
客户端多了 经常出现串流的问题  

### ISSUE THREAD

**Issue by 909254** [yisier/nps#203]
现象就是连接1000端口的客户端 实际访问串到别1005客户端，更新到了[v0.26.19]  问题依旧存在

**Comment by Luoluo-001** [comment]
我40多个客户端目前没这个问题啊，你这是不是配置问题？

**Comment by 909254** [comment]
400多个

**Comment by 909254** [comment]
> 我40多个客户端目前没这个问题啊，你这是不是配置问题？

可能你这太少了

**Comment by 909254** [comment]
而且还有断连的问题  某几个客户端一直连不上 重启nps服务就好了 过几天又会出现 再重启nps服务器

**Comment by EchoMillr** [comment]
> 而且还有断连的问题 某几个客户端一直连不上 重启nps服务就好了 过几天又会出现 再重启nps服务器

你用配置文件连接 会自动重连  不要用命令，我尝试了命令 大数据传输的时候就是会断开，而且无法重连，只能重启服务

**Comment by 909254** [comment]
> > 而且还有断连的问题 某几个客户端一直连不上 重启nps服务就好了 过几天又会出现 再重启nps服务器
> 
> 你用配置文件连接 会自动重连 不要用命令，我尝试了命令 大数据传输的时候就是会断开，而且无法重连，只能重启服务

是的 我是使用配置文件连接的

**Comment by EchoMillr** [comment]
> > > 而且还有断连的问题 某几个客户端一直连不上 重启nps服务就好了 过几天又会出现 再重启nps服务器
> > 
> > 
> > 你用配置文件连接 会自动重连 不要用命令，我尝试了命令 大数据传输的时候就是会断开，而且无法重连，只能重启服务
> 
> 是的 我是使用配置文件连接的

配置文件贴出来看看（注意去掉连接地址和密钥）

**Comment by 909254** [comment]
> > > > 而且还有断连的问题 某几个客户端一直连不上 重启nps服务就好了 过几天又会出现 再重启nps服务器
> > > 
> > > 
> > > 你用配置文件连接 会自动重连 不要用命令，我尝试了命令 大数据传输的时候就是会断开，而且无法重连，只能重启服务
> > 
> > 
> > 是的 我是使用配置文件连接的
> 
> 配置文件贴出来看看（注意去掉连接地址和密钥）

[common]
server_addr=
conn_type=tcp
vkey=
auto_reconnection=true
basic_username=11
basic_password=3
crypt=true
compress=true
remark=9518
disconnect_timeout=60
tls_enable=true
#max_conn=1000
#low_limit=1000
#rate_limit=1000
#pprof_addr=0.0.0.0:9999

[health_check_test]
health_check_timeout=1
health_check_max_failed=3
health_check_interval=1
health_check_type=tcp
health_check_target=127.0.0.1:8083,127.0.0.1:8082

[9518]
mode=tcp
target_addr=127.0.0.1:9833
server_port=9518

#[http]
#mode=httpProxy
#server_port=9004

**Comment by yisier** [comment]
推荐客户端使用命令行方式连接

**Comment by 909254** [comment]
const charset = "Z9pgVSUTlHcIkCq8FdNQsxmM2hLA4RiWzJn5oDvr3X6aGOK7tfwBeEuPyY1b0j"

func intToBase62(num int64) string {
	if num == 0 {
		return string(charset[0])
	}

	var result strings.Builder
	length := int64(len(charset))

	for num > 0 {
		result.WriteByte(charset[num%length])
		num /= length
	}

	// Reverse the result string
	reversed := result.String()
	runes := []rune(reversed)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}

// Generating Random Verification Key
func GetRandomString(l int) string {
	bytes := []byte(charset)
	result := []byte{}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	for i := 0; i < l; i++ {
		result = append(result, bytes[r.Intn(len(bytes))])
	}

	uniquePart := intToBase62(time.Now().UnixNano())
	s := append([]byte(uniquePart), result...)
	slen := string(s[:l])
	return string(slen)
}
