### ISSUE TITLE
能否加一个设备初次在线时间

### ISSUE THREAD

**Issue by EchoMillr** [yisier/nps#208]
能否加一个设备初次在线时间，就是在最后一次在线时间那里加一行初次在线时间。

**Comment by EchoMillr** [comment]
有偿处理

**Comment by yisier** [comment]
https://github.com/yisier/nps/releases/tag/v0.26.20
新版本增加了客户端创建时间，对于这种初次在线功能，属于个性化功能，建议fork 代码自行修改
