### ISSUE TITLE
域名解析通道异常

### ISSUE THREAD

**Issue by ZqinKing** [yisier/nps#21]
使用域名解析映射内网服务时；
当浏览器已经打开过nps本身映射的页面后，再不重启浏览器的情况下，继续访问其他三级域名时，显示的内容只会是nps。
目前遇到过会出现类型情况的服务器页面有 nps本身页面、pfSecse管理页面、bitwarden密码管理页面。
当已经打开过上述页面后，只能重启浏览器才能打开映射的其他的域名。
![image](https://user-images.githubusercontent.com/40748028/200764429-9623f8a7-bc0e-4961-957c-5fb15f12ec34.png)

**Comment by yisier** [comment]
无法复现

**Comment by yisier** [comment]
> > 无法复现
> 
> 有邮箱吗，把可以复现的域名私信给你。

如果可以的话，请将 nps  的 conf 目录打包一同发送来过，邮箱：zhengyp2011@163.com

**Comment by yisier** [comment]
> > > > 无法复现
> > > 
> > > 
> > > 有邮箱吗，把可以复现的域名私信给你。
> > 
> > 
> > 如果可以的话，请将 nps 的 conf 目录打包一同发送来过，邮箱：[zhengyp2011@163.com](mailto:zhengyp2011@163.com)
> 
> 已发送，请查收。

我看到你用了https的域名解析，但是却在访问地址后面都加了8443端口，nps.cnf 中https为443，不清楚8443是哪里来的，不知道为什么要这么做

**Comment by ZqinKing** [comment]
公网443端口封了，所以防火墙上开的8443映射到nps的443

发自我的iPhone

在 2022年11月10日，18:08，yisier ***@***.***> 写道：

﻿

无法复现

有邮箱吗，把可以复现的域名私信给你。

如果可以的话，请将 nps 的 conf ***@***.******@***.***>

已发送，请查收。

我看到你用了https的域名解析，但是却在访问地址后面都加了8443端口，nps.cnf 中https为443，不清楚8443是哪里来的，不知道为什么要这么做
