### ISSUE TITLE
nps有办法，解析流量内容吗？socks5的。需要解析流量内容，拦截指定网站

### ISSUE THREAD

**Issue by aohanhongzhi** [yisier/nps#210]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yisier** [comment]
没看过这块代码，但是http 和 tcp 流量是可以解析内容的，这个需要你自己研究了

**Comment by aohanhongzhi** [comment]
socks5 是加密的代理协议，内容无法解析。但是可以通过host获取网址或者ip信息。
