### ISSUE TITLE
能否修正【代理到服务器本地】需要填写【客户端 ID】

### ISSUE THREAD

**Issue by adeewu** [yisier/nps#22]
`代理到服务器本地`的`客户端ID`应该填写什么呢？

希望能修复这个问题，现在只能在服务器跑一个客户端临时解决

如图：
![image](https://user-images.githubusercontent.com/5095500/201045078-1c498bda-54e5-4ccf-8deb-79d7cd9eecaa.png)

**Comment by yisier** [comment]
新建一个客户端后能拿到客户端id，建议先看一下帮助文档

**Comment by adeewu** [comment]
@yisier 感谢，这个问题困扰我好久了，帮助文档没留意

**Comment by ac-sc** [comment]
> @yisier 感谢，这个问题困扰我好久了，帮助文档没留意

我在官方帮助文档里没找到怎样配置客户端ID呢，能指导下吗？
![image](https://github.com/yisier/nps/assets/68942777/e2eac18c-f129-4fb4-a998-c0411df79ac7)
