### ISSUE TITLE
校园网拦截npc客户端的连接

### ISSUE THREAD

**Issue by 95590110** [yisier/nps#23]
连接后客户端提示：
[46f73f7a2b954e16b7c8e375d9355b77](client.go:63]  The connection server failed and will be reconnected in five seconds, error read tcp 10.2.28.8:40784->101.2.188.54:8080: wsarecv: An existing connection was forcibly closed by the remote host.)

如何规避这样的问题。

**Comment by zhangsean** [comment]
gost，加密隧道

**Comment by 95590110** [comment]
As long as the firewall is on, so is encryption








------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "yisier/nps"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Dec 7, 2022 03:25 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [yisier/nps] 校园网拦截npc客户端的连接 (Issue #23)





 
gost，加密隧道

**Comment by 95590110** [comment]
As long as the firewall is on, so is encryption

**Comment by 95590110** [comment]
When the firewall is enabled, only ngrok clients can penetrate, not npc clients.

**Comment by GMYXDS** [comment]
> 
意思是ngrok 可以规避防火墙？
