### ISSUE TITLE
是否能添加一个 用于查询 流量统计数据的API 

### ISSUE THREAD

**Issue by xianyongjian080402** [yisier/nps#24]
我的想通过调取API的方式来统计流量（因为我有好几个服务器需要统计 所以我想自己写一个脚本 进行流量分析 毕竟我不可能一个一个的进后台）

（希望得到各位支持 谢谢谢谢🙏）

**Comment by yisier** [comment]
使用现有的API即可实现

POST /client/list/

 "Flow": {
        "ExportFlow": 794205980,
        "InletFlow": 795869033,
        "FlowLimit": 0
      }


将所有的Flow相加即可得到使用流量。

**Comment by xianyongjian080402** [comment]
好的 感谢
