### ISSUE TITLE
可以添加http重定向到https吗

### ISSUE THREAD

**Issue by xuanpro** [yisier/nps#30]
域名解析只打开https的时候，希望通过https进行访问，可以添加http重定向https吗。nps管理页面也希望有重定向

**Comment by xuanpro** [comment]
并不是nginx，而且是用的域名解析的证书，就比如说nps的管理页面就不能自动跳转

**Comment by gisxlab** [comment]
请教web管理页https怎么配置呀？

-  按照教程配置后提示“此站点的连接不安全 ERR_SSL_PROTOCOL_ERROR”：
- nps.mydomain.com SSL证书已申请并替换

`[web管理使用https](https://ehang-io.github.io/nps/#/nps_extend?id=web%e7%ae%a1%e7%90%86%e4%bd%bf%e7%94%a8https)
如果web管理需要使用https，可以在配置文件nps.conf中设置web_open_ssl=true，并配置web_cert_file和web_key_file`

`#web
web_host=nps.mydomain.com
web_username=admin
web_password=123456
web_port = 10088
web_ip=0.0.0.0
web_base_url=
web_open_ssl=true
web_cert_file=conf/server.pem
web_key_file=conf/server.key
# if web under proxy use sub path. like http://host/nps need this.
#web_base_url=/nps`
