### ISSUE TITLE
多个客户端配置可以写在一个config文件内吗？

### ISSUE THREAD

**Issue by snoweer** [yisier/nps#32]
我的NAS上跑了不同的容器应用，有多个应用需要通过NPS以域名解析的方式穿透出内网。目前我是在NAS上跑了N个NPC容器来分别连接NPS实现不同的应用域名解析穿透，可以将这些写在一个NPC的config配置文件中，以实现只要启动一个NPC客户端，就可以完成所有的连接吗？
![image](https://user-images.githubusercontent.com/10679629/205210321-210ae7c4-c4d7-4b24-8680-34e19c9237b4.png)
![image](https://user-images.githubusercontent.com/10679629/205210354-4d420c0f-3f23-4764-8949-9e370d6466f9.png)

**Comment by yisier** [comment]
![image](https://user-images.githubusercontent.com/26956516/206342352-a584cba9-e0db-4094-85bf-8842329800d2.png)
一个客户端添加多个域名解析呀，只需要启动一个客户端就好了

**Comment by snoweer** [comment]
哦，好的，我试一下，非常感谢。
