### ISSUE TITLE
一些需求

### ISSUE THREAD

**Issue by 2060yxz** [yisier/nps#33]
客户端导航：点开后左侧客户端列表，点开能够看到这个ID下面的所有tcp、域名解析等。客户端ID可以设置自动停用时间

一个域名对多个端口的问题，或者一个域名可以快速多条不同端口的穿透

**Comment by zhangsean** [comment]
1、每个客户端右侧都有两个按钮，隧道按钮可以快速查看这个客户端所有的TCP隧道，主机/域名按钮可以快速查看这个客户端所有的域名。
2、目前可以考虑使用crontab调用nps api接口，触发停用操作来实现。
3、添加域名转发的时候可以填写多个客户端IP和端口的呀，自动负载均衡。
4、一个域名多个不同端口是什么场景？如果是相同业务放在3里面自动负载均衡，如果是不同业务，应该配置不同域名呀。
