### ISSUE TITLE
通过API 增加客户端没有返回ID

### ISSUE THREAD

**Issue by victchen23** [yisier/nps#36]
添加客户端接口  POST /client/add/

1、API 增加客户端没有返回ID（无法自动返回拿到ID，需要再查询所有ID，然后筛选出来刚新增的ID）
需求：
响应携带 ID
希望能提供自增长的客户端webAPI新增接口。每次可以返回跟原有ID不重复的ID.

2、域名解析列表获取接口，不能指定客户端ID下的域名列表。（仅通过搜索来筛选）

**Comment by yisier** [comment]
[v0.26.13](https://github.com/yisier/nps/releases/tag/v0.26.13) 


优化：API返回ID, /client/add/, /index/addhost/，/index/add/ 
优化：域名解析、隧道页面，增加[唯一验证密钥]，方便搜查
