### ISSUE TITLE
web Basic 认证

### ISSUE THREAD

**Issue by zengxiao2009** [yisier/nps#39]
希望能改进一下Basic 认证功能，主要是在编辑客户端开启了Basic 认证功能，底下所有Web都进行了认证加密，这点很不方便，有些站点须要加密认证，有些不要，能不能在新增WEB页面里添加Basic 认证功能，这样可以有选择

**Comment by zengxiao2009** [comment]
最近在使用nps的过程中，经常使用到basic认证功能，

但是经过测试发现只能配置客户端的basic认证，这样将会使解析的所以域名都需要进行认证，

师傅可否适配一下针对解析的域名，单独设置basic认证呢？

**Comment by qq1063823095** [comment]
+1，某些web自身就带了basic认证，nps再强制套上一层就会导致两者冲突
