### ISSUE TITLE
客户端 ID 问题

### ISSUE THREAD

**Issue by SportPlusX** [yisier/nps#42]
遇到几个问题不知道是正常：

- web操作，客户端暂停后原客户端ID被释放，但绑定的隧道的客户端ID确没有变动，如果隧道过多就需要一个一个手动去修改才能正常使用。
- web操作暂停客户端后，状态和连接还是显示开放和在线，而暂停隧道界面却显示正常。

**Comment by wuyoutech** [comment]
类似问题，客户端重启后id会+1，同时绑定的隧道客户端id没有变动，要手动把每个隧道的id设置成新的

能否将客户端id与设备绑定起来

**Comment by kukat** [comment]
试试在nps上手动新增客户端，vkey(唯一验证密钥)留空自动生成，复制vkey在npc.conf里使用

**Comment by wuyoutech** [comment]
> 试试在nps上手动新增客户端，vkey(唯一验证密钥)留空自动生成，复制vkey在npc.conf里使用

实测有用，但要注意修改config后要npc uninstall然后重新 install，否则配置不会更新
