### ISSUE TITLE
能否支持proxy protocol v2

### ISSUE THREAD

**Issue by mclk623** [yisier/nps#44]
希望能在tcp隧道中获取真实ip

**Comment by BanKnight** [comment]
不用想了，做不到的

**Comment by jamebal** [comment]
frp支持

**Comment by luosxn** [comment]
使用其他工具就行
https://blog.ecve.cn/index.php/2024/03/17/nps%e5%86%85%e7%bd%91%e7%a9%bf%e9%80%8fhttps%e4%bc%a0%e9%80%92%e7%94%a8%e6%88%b7%e7%9c%9f%e5%ae%9eip/
