### ISSUE TITLE
在外部路径启动时会找不到配置文件

### ISSUE THREAD

**Issue by AsherZhu** [yisier/nps#48]
执行文件路径：/mnt/mmcblk0p1/app/nps/nps
配置文件路径：/mnt/mmcblk0p1/app/nps/conf/nps.conf

在其他目录启动输入 /mnt/mmcblk0p1/app/nps/nps
会提示
2023/01/12 11:38:47 load config file error the target config file: conf/nps.conf don't exist

**Comment by oslven** [comment]
是的，26.1没有这个问题

**Comment by oslven** [comment]
直接运行也会提示这个错误

**Comment by 1351383118** [comment]
刚发现这个问题，打算加到开机脚本里面，结果死活起不来

**Comment by yisier** [comment]
https://github.com/yisier/nps/releases/tag/v0.26.15

26.16 已修复

**Comment by AsherZhu** [comment]
赞！
