### ISSUE TITLE
NPS后端管理面板非常卡，反应特别慢

### ISSUE THREAD

**Issue by Coflys** [yisier/nps#50]
不知道什么原因，就是特别卡，重启服务，关闭客户端连接都无用，创建了5个客户端，隧道总数不到20个

**Comment by yisier** [comment]
可以更新到最新版试试看，老版本中页面引入了 fonts.googleapis.com 的字体库，现在这个库已经无法访问了，所以会导致页面加载很慢，新版本已经移除了这个字体

**Comment by Coflys** [comment]
感谢，我刚刚看了，应该是web没有更新，重新替换web就可以了
