### ISSUE TITLE
隧道提示受限是为什么呢？

### ISSUE THREAD

**Issue by haiwan-xm** [yisier/nps#56]
![image](https://user-images.githubusercontent.com/45061573/217508517-d881d743-8959-47bb-960c-1b919c5bbebc.png)
在win客户端下 添加 tcp隧道 都全部提示这个

**Comment by yisier** [comment]
![image](https://user-images.githubusercontent.com/26956516/221467865-c7b7cf35-d371-433d-8da9-0bf54ff6e881.png)
