### ISSUE TITLE
web登录页面能否怎么验证码和错误次数锁定

### ISSUE THREAD

**Issue by Overtimedog8** [yisier/nps#59]
web页面容易被非法用户暴力破解

1、能否实现第一次打开页面的时候不用输入验证码，当发生登录失败之后，需要输入验证码才能再次登录。
2、并且实现X分钟内登录失败X次就锁定X分钟，上述的X数字均为可调。
3、登录后，在web控制台增加一个页面，显示全部账号的登录失败信息，可以按账号名、日期时间筛选显示。

使用场景：
第一次打开nps登录页面，第一次登录只需输入用户名、密码、无需输入验证码即可登录。
发生登录错误后，再次登录需要输入验证码。
5分钟内登录失败3次则锁定10分钟。

**Comment by yisier** [comment]
v 我5000，定制开发 🐶
