### ISSUE TITLE
NPS如何安装？报错当前连接验证错误

### ISSUE THREAD

**Issue by lcy1317** [yisier/nps#6]
2022/10/28 10:57:21.590 [I] [bridge.go:198]  Current client connection validation error, close this client: 122.96.144.253:60106
2022/10/28 10:57:21.949 [I] [bridge.go:198]  Current client connection validation error, close this client: 218.2.107.245:12045
2022/10/28 10:57:26.692 [I] [bridge.go:198]  Current client connection validation error, close this client: 122.96.144.253:60109
2022/10/28 10:57:27.047 [I] [bridge.go:198]  Current client connection validation error, close this client: 218.2.107.245:28158

![image](https://user-images.githubusercontent.com/60378321/198485448-7a179b30-cdad-489d-a9b0-8049253c3299.png)

**Comment by lcy1317** [comment]
啊，这其实本身在服务器上的时候是能跑的，但是我就单纯改了一下nps配置文件然后就挂掉了，之后怎么装都装不上了 ，每次都报错，0.26.10的也跑不了。也搜不到其他人相同报错。。

**Comment by yisier** [comment]
这个错误提示已经很明显了，客户端vkey校验失败

**Comment by lcy1317** [comment]
> 这个错误提示已经很明显了，客户端vkey校验失败

问题在于我这只是装服务端啊，我客户端没配置欸。

**Comment by yisier** [comment]
install  命令被移除了，因为不同版本的系统会不兼容，你执行./nps install ，实际上是运行了服务端。
你可以使用nohub 实现在后台运行，或者使用docker。后续版本可能会做优化

**Comment by lcy1317** [comment]
我大概知道问题了，之前配置过的客户端在不断申请重连导致报错啊。。。那我直接nohup运行吧
