### ISSUE TITLE
安装了nps0.26.10怎么升级到这个分支

### ISSUE THREAD

**Issue by Overtimedog8** [yisier/nps#62]
安装了nps的 0.26.10，怎么搞升级到这个分支的最新呢？client数据和配置文件都是在/etc/nps/conf 吗？

**Comment by yisier** [comment]
更换web 目录 和 nps 可执行文件即可

**Comment by AlanWang2333** [comment]
> 更换web 目录 和 nps 可执行文件即可

请问哪个目录，我的是openwrt的分支istoreos
