### ISSUE TITLE
客户端cpu占用异常

### ISSUE THREAD

**Issue by dawei233** [yisier/nps#70]
**Describe the bug**

**To Reproduce**
1. Opening '...'
3. See error

**Expected behavior**

**Screenshots or logs**
Add screenshots or logs to help explain your problem.

**Server (please complete the following information):**
 - OS: [e.g. debian(docker)]
 - ARCH: [e.g. Amd64]
 - Tunnel [e.g. TCP,]
 - Version [e.g. 0.25.16]

**Client (please complete the following information):**
 - OS: [e.g. 群晖（docker）和openwrt客户端]
 - ARCH: [e.g. Amd64]
 - Tunnel [e.g. TCPP]
 - Version [e.g. 0.25.16]

**Additional context**
客户端cpu占用异常 多少cpu都能吃干净， 在原作者停止更新前就这样了 ，现在的新版本依旧有这个问题 ，客户端会一点点的增加cpu占用直到吃满。重启可解

**Comment by yisier** [comment]
需要描述下使用场景，或者如何才能复现

**Comment by dawei233** [comment]
额就是正常使用 
![image](https://user-images.githubusercontent.com/31338729/225535370-20391f90-ffab-4e11-9fa6-bf0226869ad3.png)
这个是在群晖docker里面我给设置了cpu优先级为底，都占用这么高了

**Comment by dawei233** [comment]
![image](https://user-images.githubusercontent.com/31338729/225536848-6f199ab2-5587-42fb-a4f0-f254d7d97c72.png)
十分夸张

**Comment by yisier** [comment]
需要知道使用场景，以及如何才能复现，而不是现象本身

**Comment by dawei233** [comment]
![image](https://user-images.githubusercontent.com/31338729/225537797-e4c539a6-8bb1-42ec-bc85-202919826d50.png)
卧槽我看客户端日志是这样的不会是有人在爆破我的内网设备吧

**Comment by dawei233** [comment]
NPC是放在内网的 群晖docker里面或者 软路由docker里面  大概有30个映射平时基本都很少在外面访问大部分时间都是休眠的
![image](https://user-images.githubusercontent.com/31338729/225539025-729da310-6d9e-4277-9881-9569ecd27710.png)
客户端配置，

**Comment by dawei233** [comment]
我翻了几天的日志 发现全是不断在换ip在 连接我这个的ssh端口

**Comment by dawei233** [comment]
![%6@P{)@12UPSCK7HUE@)``W](https://user-images.githubusercontent.com/31338729/225539576-8c44c8cd-62ce-4a45-8819-3fc9bb8c5698.jpg)
能加个自动防爆不这种一直换ip的手动加黑名单不靠谱啊
