### ISSUE TITLE
CPU单核心跑满

### ISSUE THREAD

**Issue by AsherZhu** [yisier/nps#71]
服务端占用爆满，服务器是 ARM64 四核cpu，单核始终跑满
12969     1 root     S     769m  20%  25% /mnt/mmcblk0p1/app/nps/nps -conf_path=/mnt/mmcblk0p1/app/nps

我暂停了全部客户端仍然单核跑满
![image](https://user-images.githubusercontent.com/26699364/226170563-9f136410-a2b3-4c05-9f20-904ae45f629d.png)

重启后占用正常
 6586     1 root     S     699m  18%   0% /mnt/mmcblk0p1/app/nps/nps -conf_path=/mnt/mmcblk0p1/app/nps

大概率是存在死循环bug，这个使用率是慢慢涨起来然后就一直维持单核心满载，大概一两天就会涨上去。

**Comment by yisier** [comment]
压缩、加密、缓存,这些功能都关掉试试看

**Comment by yisier** [comment]
另外，查看一下日志，是否被存在被暴利破解、扫描端口等等

**Comment by D10NGYANG** [comment]
同样存在这个问题，但是不需要两天，基本一启动就跑满了

**Comment by D10NGYANG** [comment]
> 同样存在这个问题，但是不需要两天，基本一启动就跑满了

我这边的问题找到了，来自SLB的健康检查，把阿里云的SLB关于UDP隧道的健康检查关了就没事了，TCP连接数也恢复正常了。
