### ISSUE TITLE
HTTPS协议不统计流量

### ISSUE THREAD

**Issue by nkxingxh** [yisier/nps#75]
**Describe the bug**
使用自定义配置文件，域名解析模式下不统计流量。

配置文件如下：

```ini
[common]
server_addr=192.168.6.109:8024
conn_type=tcp
remark=
vkey=xxxxxxxxxxxxxx
web_username=
web_password=
max_conn=256
rate_limit=2048
crypt=true
compress=true
auto_reconnection=true
disconnect_timeout=60

[tcp]
mode=tcp
target_addr=192.168.6.3:80
server_port=10000

[https]
host=example.com
target_addr=127.0.0.1:443
scheme=https
```

*注：`example.com` 为示例域名，实际场景使用的自己的域名，已指向 `192.168.6.109`*

访问 `http://example.com:10000` 则**正常**统计流量

访问 `https://example.com` 则**不统计**流量

**Comment by nkxingxh** [comment]
**补充**

经过进一步测试发现，无论使用**域名解析模式**或**TCP模式**

HTTP协议可以正确统计流量，而HTTPS协议则不统计流量。

**Comment by nkxingxh** [comment]
**补充**

在 TCP 模式下，使用非 HTTPS 协议都可以正确统计流量。

**Comment by yisier** [comment]
已修复
https://github.com/yisier/nps/releases/tag/v0.26.16
