### ISSUE TITLE
服务端运行正常，可是在op里装的最新的docker总显示连接失败

### ISSUE THREAD

**Issue by luowenyu001** [yisier/nps#76]
[npc.go:231]  the version of client is 0.26.14, the core version of client is 0.26.0
2023/04/11 05:53:46.705 [E] [control.go:231]  read tcp 192.168.225.56:34602->****:8024: read: connection reset by peer
2023/04/11 05:53:46.705 [E] [client.go:63]  The connection server failed and will be reconnected in five seconds, error read tcp 192.168.225.56:34602->****:8024: read: connection reset by peer
2023/04/11 05:53:56.727 [E] [control.go:231]  read tcp 192.168.225.56:40302->****:8024: read: connection reset by peer
2023/04/11 05:53:56.727 [E] [client.go:63]  The connection server failed and will be reconnected in five seconds, error read tcp 192.168.225.56:40302->****:8024: read: connection reset by peer

**Comment by nkxingxh** [comment]
感觉是网络问题？`connection reset by peer`

_连接被重置_
