### ISSUE TITLE
是不是忘记改版本号了？

### ISSUE THREAD

**Issue by LOVECHEN** [yisier/nps#81]
cat lib/version/version.go
package version

const VERSION = "0.26.14"

// Compulsory minimum version, Minimum downward compatibility to this version
func GetVersion() string {
        return "0.26.0"
}

**Comment by remember-5** [comment]
安装的0.26.15提示
```nps -version
Version: 0.26.14
Core version: 0.26.0
Same core version of client and server can connect each other
```

**Comment by yisier** [comment]
0.26.15 版本确实忘记改版本号了，16版本已发布

**Comment by klxyy** [comment]
> 0.26.15 版本确实忘记改版本号了，16版本已发布

大佬，抽空更新下Docker版本

**Comment by klxyy** [comment]
> 0.26.15 版本确实忘记改版本号了，16版本已发布

@yisier 大佬，抽空更新下Docker版本
