### ISSUE TITLE
爱快使用时报错

### ISSUE THREAD

**Issue by zy1818** [yisier/nps#82]
爱快 docker 里面安装可以正常运行，进入控制台报错  提示找不到/bin/sh这个目录，主要想进控制台安装一下tz好设置一下时区，不设置时区日志相差8小时，看着很别扭。以下是报错信息：  OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown

测试了多个版本都一样，官方0.26.10也是这样

**Comment by josbu** [comment]
我也是爱快虚拟系统  没有错

**Comment by zy1818** [comment]
能帮我看看到底哪里问题啊，主要想把日志时间和系统时间对应，我frp和n2n都弄好了，这个无法进入控制台装tz，那个tz变量也无法生效

**Comment by yisier** [comment]
增加 docker 运行参数 ： -v /etc/localtime:/etc/localtime:ro

**Comment by zy1818** [comment]
您有一份重要文件，需要及时收阅！点击查看全文
                                                    

***@***.***，请勿直接回复。
