### ISSUE TITLE
NPS官方版本会自动在服务器上生成多个socks代理

### ISSUE THREAD

**Issue by helloweizhang** [yisier/nps#84]
NPS官方版本会自动在服务器上生成多个socks代理. 怀疑是木马后门
请问你们这个版本有修复这个漏洞吗.

**Comment by GMYXDS** [comment]
同问，这个问题怎么处理

**Comment by GMYXDS** [comment]
鉴权漏洞已经修复，看样子
https://github.com/ehang-io/nps/issues/1090
https://github.com/yisier/nps/releases/tag/v0.26.14
这个issue可以关了
