### ISSUE TITLE
v0.26.15流量统计问题 

### ISSUE THREAD

**Issue by xiaohu911** [yisier/nps#86]
在面板内查看流量统计，出入口是相同的。另一台搭建的官方版0.26.10出入口流量就不相同，请问是不是bug哦？
![微信图片_20230520171114](https://github.com/yisier/nps/assets/87983541/0d900035-fa5d-48c2-906a-9d836bf61eb3)

**Comment by xiaohu911** [comment]
这是官方版的
![微信图片_20230520171332](https://github.com/yisier/nps/assets/87983541/892985a9-4426-466a-bf1e-c8cdf3c7b689)

**Comment by yisier** [comment]
内网穿透的上下行流量是对等的，原理就是如此
