### ISSUE TITLE
病毒检测不通过

### ISSUE THREAD

**Issue by littlejacky** [yisier/nps#88]
这边的客户端版本跟原本的一样，会被杀毒……这有解吗？

**Comment by laocuiGitHub** [comment]
我直接把杀毒软件给退了，但不知道是不是因为这个软件太长时间没有更新真有病毒了还是误报。感觉不太安全！

**Comment by xiaohu911** [comment]
直接裸跑，毒都会怕

**Comment by GMYXDS** [comment]
https://github.com/ehang-io/nps/issues/1101
根据这个issue 好像说的是 穿透工具都包含hacktool?
你查一下frp 和 ngrok 试试
他们说好像是正常的

**Comment by yisier** [comment]
报毒暂时解决不了，不管是 nps 还是 frp ，都被一部分安全厂商列入了病毒名单
