### ISSUE TITLE
希望能够增加一个访问记录的功能

### ISSUE THREAD

**Issue by JiangShi-GitHub** [yisier/nps#96]
希望能够增加一个某ip何时访问了某隧道之类的功能，因为目标服务器查登录全是127.0.0.1，然后nps自己好像也没有记录。

**Comment by iotbi** [comment]
确实很需要这个，有时候为了排查问题

**Comment by Crazy-FuQing** [comment]
nps.log等级开高一点就能看到

**Comment by yisier** [comment]
nps 有日志记录，建议看一下使用文档
