### ISSUE TITLE
Windows下部署 怎么修改配置文件都没用

### ISSUE THREAD

**Issue by newsyf999** [yisier/nps#98]
Windows下部署 怎么修改配置文件都没用,比如修改密码,都不行,一直是原始的123 ,.linux下没这个问题

**Comment by Crazy-FuQing** [comment]
部署方式是安装服务吗，install参数会将exe和conf/ 复制到C:\Program Files

**Comment by yisier** [comment]
linux 与 windows 都没复现这个问题，nps 启动时会打印配置文件目录，可以检查读取的配置文件在哪里

![image](https://github.com/yisier/nps/assets/26956516/76be5261-1473-44eb-8e78-7ced60082bac)

**Comment by newsyf999** [comment]
> linux 与 windows 都没复现这个问题，nps 启动时会打印配置文件目录，可以检查读取的配置文件在哪里
> 
> ![image](https://user-images.githubusercontent.com/26956516/246113486-76be5261-1473-44eb-8e78-7ced60082bac.png)

windows下用什么命令,查看你说的这个日志,帮助里没找到

**Comment by newsyf999** [comment]
> linux 与 windows 都没复现这个问题，nps 启动时会打印配置文件目录，可以检查读取的配置文件在哪里
> 
> ![image](https://user-images.githubusercontent.com/26956516/246113486-76be5261-1473-44eb-8e78-7ced60082bac.png)
终于搞好了,我把二个地方的配置文件都改了下就行了,安装目录,和C:\Program Files 下,都改了一次 谢谢!
